//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperatingManagement.Web.Views.UserAndRole {
    
    
    public partial class UserNRole {
        
        /// <summary>
        /// navMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OperatingManagement.WebKernel.Controls.PageNavigator navMain;
        
        /// <summary>
        /// PageMenu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OperatingManagement.WebKernel.Controls.PageMenu PageMenu1;
    }
}
